name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatchling==1.27.0 hatch==1.14.0
      - name: Set VERSION env
        run: echo "VERSION=$(grep -E '^version\\s*=\\s*\".*\"' pyproject.toml | awk -F '\"' '{print $2}')" >> $GITHUB_ENV
      - name: Check tag matches version
        run: |
          if [ "v$(grep -E '^version\\s*=\\s*\".*\"' pyproject.toml | awk -F '\"' '{print $2}')" != "${{ github.ref_name }}" ]; then
            echo "Error: Git tag does not match project version (v$(grep -E '^version\\s*=\\s*\".*\"' pyproject.toml | awk -F '\"' '{print $2}'))"
            exit 1
          fi
      - name: Check if version exists on PyPI
        id: version_check
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          if curl -s -f https://pypi.org/pypi/light-s3-client/$VERSION/json > /dev/null; then
            echo "Version ${VERSION} already exists on PyPI"
            echo "pypi_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Version ${VERSION} not found on PyPI - proceeding with PyPI deployment"
            echo "pypi_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Build package
        if: steps.version_check.outputs.pypi_exists != 'true'
        run: |
          pip install hatchling
          hatch build
      - name: Publish to PyPI
        if: steps.version_check.outputs.pypi_exists != 'true'
        uses: pypa/gh-action-pypi-publish@v1.12.4
