name: Version Check

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - 'light_s3_client/**'
      - 'setup.py'
      - 'pyproject.toml'

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check version increment
        id: version_check
        run: |
          PR_VERSION=$(grep -o "__version__.*" light_s3_client/__init__.py | awk '{print $3}' | tr -d "'\"")
          echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV
          git checkout origin/main
          MAIN_VERSION=$(grep -o "__version__.*" light_s3_client/__init__.py | awk '{print $3}' | tr -d "'\"")
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV
          python3 -c "
          from packaging import version
          pr_ver = version.parse('${PR_VERSION}')
          main_ver = version.parse('${MAIN_VERSION}')
          if pr_ver <= main_ver:
              print(f'❌ Version must be incremented! Main: {main_ver}, PR: {pr_ver}')
              exit(1)
          print(f'✅ Version properly incremented from {main_ver} to {pr_ver}')
          "
      - name: Manage PR Comment
        uses: actions/github-script@v7
        if: always()
        env:
          MAIN_VERSION: ${{ env.MAIN_VERSION }}
          PR_VERSION: ${{ env.PR_VERSION }}
          CHECK_RESULT: ${{ steps.version_check.outcome }}
        with:
          script: |
            const success = process.env.CHECK_RESULT === 'success';
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const comments = await github.rest.issues.listComments({
              owner: owner,
              repo: repo,
              issue_number: prNumber,
            });
            const versionComment = comments.data.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('Version Check')
            );
            if (versionComment) {
              if (success) {
                await github.rest.issues.deleteComment({
                  owner: owner,
                  repo: repo,
                  comment_id: versionComment.id,
                });
              } else {
                await github.rest.issues.updateComment({
                  owner: owner,
                  repo: repo,
                  comment_id: versionComment.id,
                  body: `❌ Version Check Failed\nMain: ${process.env.MAIN_VERSION}\nPR: ${process.env.PR_VERSION}`,
                });
              }
            } else if (!success) {
              await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: prNumber,
                body: `❌ Version Check Failed\nMain: ${process.env.MAIN_VERSION}\nPR: ${process.env.PR_VERSION}`,
              });
            }
